base.url=https://www.saucedemo.com/
browser=chrome
headless=false
timeout.seconds=10

valid.username=standard_user
valid.password=secret_sauce
invalid.username=locked_out_user
invalid.password=secret_sauce