base.url=https://www.saucedemo.com/
browser=chrome
headless=false
timeout.seconds=10
java=23.0.1
os=Windows 11
architecture=amd64
language=ja

valid.username=standard_user
valid.password=secret_sauce
invalid.username=locked_out_user
invalid.password=secret_sauce